name: ijan-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Или нужная версия Python
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy
  - pydantic
  - requests
  - aiohttp
  - beautifulsoup4
  - Flask
  - gTTS
  - pydub
  - pillow
  - lxml
  - openai
  - python-dotenv
  - pip:
      - pyttsx3  # Установка через pip
      - deep-translator
      - pyairtable
      - pytelegrambotapi
      - pywhatkit
      - googletrans
      - twilio
