name: ijan-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # Вы можете выбрать другую версию Python, если необходимо
  - pip
  - fastapi
  - uvicorn
  - sqlalchemy  # Если используется база данных SQL
  - pydantic
  - requests
  - aiohttp
  - beautifulsoup4
  - Flask  # Если используется
  - gTTS  # Если используется
  - pydub  # Если используется
  - pyttsx3  # Если используется
  - pillow
  - lxml
  - openai
  - python-dotenv
  - pip:
      - deep-translator
      - pyairtable
      - pytelegrambotapi
      - pywhatkit
      - googletrans
      - twilio
      # Добавьте дополнительные пакеты, если нужно
